version: '3.3'
services:
  pg:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./database.env

  backend:
    image: test_auth:v0.1
    build: .
    depends_on:
      - pg
    ports:
      - 8080:8080
    environment:
      DB_HOST: pg
    env_file:
      - ./api.env

volumes:
  pgdata: